services:
  # --- ВЕРТИКАЛЬНЫЙ ШАРД 1: ПОЛЬЗОВАТЕЛИ (MASTER) ---
  users_db_master:
    image: postgres:15
    container_name: users_db_master
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init-master-users.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5431:5432"

  # --- ВЕРТИКАЛЬНЫЙ ШАРД 2: КАТАЛОГ КНИГ (MASTER) ---
  catalog_db_master:
    image: postgres:15
    container_name: catalog_db_master
    # НАПРЯМУЮ В КОНФИГЕ: Передаем параметры конфигурации при старте Postgres
    # 1. Разрешаем подключения со всех IP-адресов внутри сети Docker (host replication all 0.0.0.0/0 trust)
    # 2. Включаем уровень логирования WAL для репликации (-c wal_level=replica)
    # 3. Выделяем 5 слотов для отправки логов (-c max_wal_senders=5)
    command: |
      postgres 
        -c wal_level=replica 
        -c max_wal_senders=5 
        -c max_replication_slots=5
        -c hba_file=/docker-entrypoint-initdb.d/pg_hba.conf
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init-master-catalog.sql:/docker-entrypoint-initdb.d/init.sql
      # Создаем файл настроек доступа прямо «на лету» внутри контейнера
      - ./pg_hba.conf:/docker-entrypoint-initdb.d/pg_hba.conf
    ports:
      - "5432:5432"

  # --- РЕПЛИКА (SLAVE) ДЛЯ ШАРДА КАТАЛОГА ---
    # --- РЕПЛИКА (SLAVE) ДЛЯ ШАРДА КАТАЛОГА ---
  catalog_db_slave:
    image: postgres:15
    container_name: catalog_db_slave
    # НАПРЯМУЮ УКАЗЫВАЕМ ПОЛЬЗОВАТЕЛЯ ДЛЯ ЗАПУСКА:
    user: postgres
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    depends_on:
      - catalog_db_master
    command: |
      bash -c "sleep 10 && 
               rm -rf /var/lib/postgresql/data/* && 
               pg_basebackup -h catalog_db_master -D /var/lib/postgresql/data -U ${DB_USER} -v -P -R -X stream &&
               exec docker-entrypoint.sh postgres"
    ports:
      - "5433:5432"

